In [1]:
# Libraries
# Numpy - numerical python

In [2]:
pip install numpy

Requirement already satisfied: numpy in c:\tools\anaconda3\lib\site-packages (2.3.5)
Note: you may need to restart the kernel to use updated packages.

In [4]:
import numpy as np

In [7]:
# numpy stores data in form of numpy arrays
# numpy sets base to use other libs like pandas
# 3 types of numpy arrays - 1D,2D,3D
# numpy arrays can store data of one type only

L = ["Kushal", "Anmol", "Amay"]

In [8]:
np.array(L)  # Here U6 is data type like U is string and 6 is the max length of an element

array(['Kushal', 'Anmol', 'Amay'], dtype='<U6')

In [10]:
arr = np.array(L)
type(arr)

numpy.ndarray

In [119]:
L2 = [100,200,300,"Sam"]   # if i give string value it will convert everything into string
np.array(L2)

array(['100', '200', '300', 'Sam'], dtype='<U21')

In [120]:
L3 = [100,200,300,True,False]
np.array(L3)                        #converted into int
# String has more priority than numbers

array([100, 200, 300,   1,   0])

In [17]:
arr.dtype

dtype('<U6')

In [18]:
arr.ndim  # no. of dimensions

1

In [121]:
arr[1]

np.str_('Anmol')

In [22]:
# 2D Array - Matrix
L_2D = [[100, 200, 300, 400, 500], [400,500,600,700,800]]
x = np.array(L_2D)

In [23]:
x

array([[100, 200, 300, 400, 500],
       [400, 500, 600, 700, 800]])

In [24]:
x.ndim

2

In [29]:
L_2D = [[100, 200, 300, 400, 500], [400,500,600,700,800],[900,1000,2000,3000,4000]]
y = np.array(L_2D)

In [30]:
y

array([[ 100,  200,  300,  400,  500],
       [ 400,  500,  600,  700,  800],
       [ 900, 1000, 2000, 3000, 4000]])

In [31]:
y.ndim

2

In [34]:
# Shape tells rows and cols
y.shape

(3, 5)

In [36]:
L_3D = [[[100, 200, 300, 400, 500], [400,500,600,700,800],[900,1000,2000,3000,4000]]]
z = np.array(L_3D)

In [40]:
z

array([[[ 100,  200,  300,  400,  500],
        [ 400,  500,  600,  700,  800],
        [ 900, 1000, 2000, 3000, 4000]]])

In [37]:
z.ndim

3

In [39]:
z[0,0,3]

np.int64(400)

In [44]:
# Random
np.random.rand()

0.758113376007249

In [45]:
np.random.randint(100,200)

122

dir(np)

In [53]:
# seeding -fixing the randomness
np.random.seed(4)
# np.random.rand()
np.random.randint(200,300)

246

In [71]:
np.random.seed(4)
a = np.random.randint(200,300,30)   # Generates 30 random nos.

In [72]:
a.ndim

1

In [76]:
# Reshape
mat = a.reshape(5,6)  # Changed 1D into 2D matrix of size 5*6

In [80]:
mat

array([[246, 255, 269, 201, 287, 272],
       [250, 209, 258, 294, 255, 255],
       [257, 236, 250, 244, 238, 252],
       [203, 200, 255, 221, 221, 273],
       [238, 256, 266, 246, 230, 208]], dtype=int32)

In [77]:
mat.ndim

2

In [79]:
mat[2][3]

np.int32(244)

In [82]:
sub_mat = mat[2: , 3:]
sub_mat

array([[244, 238, 252],
       [221, 221, 273],
       [246, 230, 208]], dtype=int32)

In [83]:
mat[2:,:]

array([[257, 236, 250, 244, 238, 252],
       [203, 200, 255, 221, 221, 273],
       [238, 256, 266, 246, 230, 208]], dtype=int32)

In [84]:
# 3D array - collection of multiple 2d arrays
a

array([246, 255, 269, 201, 287, 272, 250, 209, 258, 294, 255, 255, 257,
       236, 250, 244, 238, 252, 203, 200, 255, 221, 221, 273, 238, 256,
       266, 246, 230, 208], dtype=int32)

In [85]:
three_dim = a.reshape(3,5,2)  # 3 5*2 dimension arrays
three_dim.ndim

3

In [87]:
three_dim

array([[[246, 255],
        [269, 201],
        [287, 272],
        [250, 209],
        [258, 294]],

       [[255, 255],
        [257, 236],
        [250, 244],
        [238, 252],
        [203, 200]],

       [[255, 221],
        [221, 273],
        [238, 256],
        [266, 246],
        [230, 208]]], dtype=int32)

In [86]:
three_dim[1,1,0]

np.int32(257)

In [88]:
# Like we have range in np there is arange with same last element exclusive
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [90]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [91]:
np.ones(5)  # Float data type by default

array([1., 1., 1., 1., 1.])

In [92]:
np.ones(5, dtype="int")

array([1, 1, 1, 1, 1])

In [93]:
# identity
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [94]:
arr1 = np.arange(1,5)

In [95]:
arr2 = np.arange(6,10)

In [96]:
np.vstack([arr1,arr2])

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [97]:
np.hstack([arr1,arr2])

array([1, 2, 3, 4, 6, 7, 8, 9])

In [98]:
# Pandas
# has all functionalities of numpy also like calculation, data visualization, etc
# panel data analysis
import pandas as pd

In [105]:
# Series
# Dataframe

# Series is one column of data

L=["Sam","John","Leo"]
S = pd.Series(L)

In [106]:
S

0     Sam
1    John
2     Leo
dtype: object

In [107]:
type(S)

pandas.core.series.Series

In [108]:
S[0]

'Sam'

In [109]:
S = pd.Series(L, index=["Stu1","Stu2","Stu3"])   # Custom indexing but default 0,1,2... is still present

In [110]:
S

Stu1     Sam
Stu2    John
Stu3     Leo
dtype: object

In [111]:
S[0]

C:\Users\Administrator\AppData\Local\Temp\2\ipykernel_5336\2981122203.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  S[0]

'Sam'

In [112]:
S["Stu1"]

'Sam'

In [115]:
# Indexing
# User defined - 1,2,3
# Default - 0,1,2
S = pd.Series(L, index=[1,2,3])
S[1]

'Sam'

In [116]:
S

1     Sam
2    John
3     Leo
dtype: object

In [117]:
#loc for user defined
#iloc for default
S.loc[1]

'Sam'

In [118]:
S.iloc[1]

'John'

In [122]:
# Create a series with 20 random numbers b/w 100-200
# give udi as stu1-stu20
arr = np.random.randint(100,200,20)

In [123]:
index = ["Stu" + str(i) for i in range(1,21)]

In [124]:
s=pd.Series(arr,index)

In [125]:
s

Stu1     149
Stu2     166
Stu3     158
Stu4     187
Stu5     132
Stu6     140
Stu7     142
Stu8     145
Stu9     133
Stu10    132
Stu11    128
Stu12    103
Stu13    179
Stu14    198
Stu15    195
Stu16    157
Stu17    150
Stu18    117
Stu19    181
Stu20    189
dtype: int32

In [127]:
s.head()  # by default first 5 shows or we can pass no. - eg - (3)

Stu1    149
Stu2    166
Stu3    158
Stu4    187
Stu5    132
dtype: int32

In [128]:
s.tail()   # by default last 5 shows or we can pass no. - eg - (3)

Stu16    157
Stu17    150
Stu18    117
Stu19    181
Stu20    189
dtype: int32

In [129]:
# Sort
s.sort_values()

Stu12    103
Stu18    117
Stu11    128
Stu10    132
Stu5     132
Stu9     133
Stu6     140
Stu7     142
Stu8     145
Stu1     149
Stu17    150
Stu16    157
Stu3     158
Stu2     166
Stu13    179
Stu19    181
Stu4     187
Stu20    189
Stu15    195
Stu14    198
dtype: int32

In [130]:
s.sort_values(ascending=False)

Stu14    198
Stu15    195
Stu20    189
Stu4     187
Stu19    181
Stu13    179
Stu2     166
Stu3     158
Stu16    157
Stu17    150
Stu1     149
Stu8     145
Stu7     142
Stu6     140
Stu9     133
Stu10    132
Stu5     132
Stu11    128
Stu18    117
Stu12    103
dtype: int32

In [132]:
#unique
s.unique()

array([149, 166, 158, 187, 132, 140, 142, 145, 133, 128, 103, 179, 198,
       195, 157, 150, 117, 181, 189], dtype=int32)

In [134]:
# nunique- gives no. of unique values
s.nunique()

19

In [135]:
# Dataframes
# this is a proper tabular format of data
# dictionary key value pairs

d={"ID":[1,2,3], "Name":["A","B","C"], "is_Male":[True, False, True]}

In [136]:
DF = pd.DataFrame(d)

In [137]:
DF

   ID Name  is_Male
0   1    A     True
1   2    B    False
2   3    C     True

In [138]:
DF.iloc[0,1]

'A'

In [139]:
DF.loc[0,"Name"]

'A'

In [141]:
# We will load the data
# load the data from csv
bank = pd.read_csv("P1-UK-Bank-Customers (1) (8).csv")

In [142]:
bank

,Customer ID,Name,Surname,Gender,Age,Region,Job Classification,Date Joined,Balance
0,100000001,Simon,Walsh,Male,21,England,White Collar,05.Jan.15,113810.15
1,400000002,Jasmine,Miller,Female,34,Northern Ireland,Blue Collar,06.Jan.15,36919.73
2,100000003,Liam,Brown,Male,46,England,White Collar,07.Jan.15,101536.83
3,300000004,Trevor,Parr,Male,32,Wales,White Collar,08.Jan.15,1421.52
4,100000005,Deirdre,Pullman,Female,38,England,Blue Collar,09.Jan.15,35639.79
...,...,...,...,...,...,...,...,...,...
4009,200004010,Sam,Lewis,Male,64,Scotland,Other,30.Dec.15,19711.66
4010,200004011,Keith,Hughes,Male,52,Scotland,Blue Collar,30.Dec.15,56069.72
4011,200004012,Hannah,Springer,Female,50,Scotland,Other,30.Dec.15,59477.82
4012,200004013,Christian,Reid,Male,51,Scotland,Blue Collar,30.Dec.15,239.45
4013,300004014,Stephen,May,Male,33,Wales,Blue Collar,30.Dec.15,30293.19

In [143]:
bank.head()

,Customer ID,Name,Surname,Gender,Age,Region,Job Classification,Date Joined,Balance
0,100000001,Simon,Walsh,Male,21,England,White Collar,05.Jan.15,113810.15
1,400000002,Jasmine,Miller,Female,34,Northern Ireland,Blue Collar,06.Jan.15,36919.73
2,100000003,Liam,Brown,Male,46,England,White Collar,07.Jan.15,101536.83
3,300000004,Trevor,Parr,Male,32,Wales,White Collar,08.Jan.15,1421.52
4,100000005,Deirdre,Pullman,Female,38,England,Blue Collar,09.Jan.15,35639.79

In [144]:
bank.tail()

,Customer ID,Name,Surname,Gender,Age,Region,Job Classification,Date Joined,Balance
4009,200004010,Sam,Lewis,Male,64,Scotland,Other,30.Dec.15,19711.66
4010,200004011,Keith,Hughes,Male,52,Scotland,Blue Collar,30.Dec.15,56069.72
4011,200004012,Hannah,Springer,Female,50,Scotland,Other,30.Dec.15,59477.82
4012,200004013,Christian,Reid,Male,51,Scotland,Blue Collar,30.Dec.15,239.45
4013,300004014,Stephen,May,Male,33,Wales,Blue Collar,30.Dec.15,30293.19

In [145]:
bank.shape

(4014, 9)

In [146]:
bank.shape[0]

4014

In [147]:
bank.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4014 entries, 0 to 4013
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Customer ID         4014 non-null   int64
 1   Name                4014 non-null   object
 2   Surname             4014 non-null   object
 3   Gender              4014 non-null   object
 4   Age                 4014 non-null   int64
 5   Region              4014 non-null   object
 6   Job Classification  4014 non-null   object
 7   Date Joined         4014 non-null   object
 8   Balance             4014 non-null   float64
dtypes: float64(1), int64(2), object(6)
memory usage: 282.4+ KB

In [148]:
bank.loc[:,["Name","Age","Balance"]]

           Name  Age    Balance
0         Simon   21  113810.15
1       Jasmine   34   36919.73
2          Liam   46  101536.83
3        Trevor   32    1421.52
4       Deirdre   38   35639.79
...         ...  ...        ...
4009        Sam   64   19711.66
4010      Keith   52   56069.72
4011     Hannah   50   59477.82
4012  Christian   51     239.45
4013    Stephen   33   30293.19

[4014 rows x 3 columns]

In [150]:
bank.loc[bank["Gender"]=="Male",:]

,Customer ID,Name,Surname,Gender,Age,Region,Job Classification,Date Joined,Balance
0,100000001,Simon,Walsh,Male,21,England,White Collar,05.Jan.15,113810.15
2,100000003,Liam,Brown,Male,46,England,White Collar,07.Jan.15,101536.83
3,300000004,Trevor,Parr,Male,32,Wales,White Collar,08.Jan.15,1421.52
9,100000010,Dominic,Parr,Male,42,England,White Collar,12.Jan.15,10912.45
10,100000011,Dominic,Lewis,Male,40,England,White Collar,12.Jan.15,39667.83
...,...,...,...,...,...,...,...,...,...
4007,100004008,Sam,Sanderson,Male,28,England,Blue Collar,30.Dec.15,42128.29
4009,200004010,Sam,Lewis,Male,64,Scotland,Other,30.Dec.15,19711.66
4010,200004011,Keith,Hughes,Male,52,Scotland,Blue Collar,30.Dec.15,56069.72
4012,200004013,Christian,Reid,Male,51,Scotland,Blue Collar,30.Dec.15,239.45
4013,300004014,Stephen,May,Male,33,Wales,Blue Collar,30.Dec.15,30293.19

In [151]:
# and or operators
# & |
bank.loc[(bank["Gender"]=="Male") | (bank["Region"]=="England"), ["Name","Balance"]]

           Name    Balance
0         Simon  113810.15
2          Liam  101536.83
3        Trevor    1421.52
4       Deirdre   35639.79
6       Dorothy   42879.84
...         ...        ...
4007        Sam   42128.29
4009        Sam   19711.66
4010      Keith   56069.72
4012  Christian     239.45
4013    Stephen   30293.19

[3256 rows x 2 columns]

In [152]:
bank.sort_values("Balance")

,Customer ID,Name,Surname,Gender,Age,Region,Job Classification,Date Joined,Balance
1319,100001320,Jane,King,Female,38,England,White Collar,22.Jul.15,11.52
74,400000075,Olivia,Dowd,Female,30,Northern Ireland,White Collar,12.Feb.15,21.03
774,200000775,Warren,Roberts,Male,37,Scotland,Blue Collar,01.Jun.15,69.01
2045,400002046,Megan,Hart,Female,19,Northern Ireland,Blue Collar,13.Sep.15,69.78
3467,300003468,Stewart,Johnston,Male,41,Wales,Blue Collar,30.Nov.15,77.46
...,...,...,...,...,...,...,...,...,...
913,400000914,Anna,Randall,Female,25,Northern Ireland,Blue Collar,18.Jun.15,149698.12
3831,100003832,Sebastian,Arnold,Male,44,England,Blue Collar,20.Dec.15,161517.82
2009,200002010,Connor,North,Male,50,Scotland,Other,11.Sep.15,172085.48
3449,100003450,Carl,Fraser,Male,35,England,White Collar,30.Nov.15,181680.99
1306,100001307,Dorothy,Jackson,Female,31,England,White Collar,22.Jul.15,183467.70

In [153]:
bank.sort_values("Balance", ascending=False)

,Customer ID,Name,Surname,Gender,Age,Region,Job Classification,Date Joined,Balance
1306,100001307,Dorothy,Jackson,Female,31,England,White Collar,22.Jul.15,183467.70
3449,100003450,Carl,Fraser,Male,35,England,White Collar,30.Nov.15,181680.99
2009,200002010,Connor,North,Male,50,Scotland,Other,11.Sep.15,172085.48
3831,100003832,Sebastian,Arnold,Male,44,England,Blue Collar,20.Dec.15,161517.82
913,400000914,Anna,Randall,Female,25,Northern Ireland,Blue Collar,18.Jun.15,149698.12
...,...,...,...,...,...,...,...,...,...
3467,300003468,Stewart,Johnston,Male,41,Wales,Blue Collar,30.Nov.15,77.46
2045,400002046,Megan,Hart,Female,19,Northern Ireland,Blue Collar,13.Sep.15,69.78
774,200000775,Warren,Roberts,Male,37,Scotland,Blue Collar,01.Jun.15,69.01
74,400000075,Olivia,Dowd,Female,30,Northern Ireland,White Collar,12.Feb.15,21.03
1319,100001320,Jane,King,Female,38,England,White Collar,22.Jul.15,11.52

In [155]:
bank.sort_values(["Region","Balance"])

,Customer ID,Name,Surname,Gender,Age,Region,Job Classification,Date Joined,Balance
1319,100001320,Jane,King,Female,38,England,White Collar,22.Jul.15,11.52
3884,100003885,Abigail,Mills,Female,29,England,White Collar,23.Dec.15,98.68
1418,100001419,Lillian,Mathis,Female,43,England,White Collar,28.Jul.15,114.69
2734,100002735,Chloe,Gill,Female,27,England,Blue Collar,22.Oct.15,134.94
296,100000297,Sophie,Thomson,Female,33,England,White Collar,23.Apr.15,152.91
...,...,...,...,...,...,...,...,...,...
1033,300001034,Julian,Carr,Male,35,Wales,Blue Collar,29.Jun.15,134324.66
2538,300002539,Julian,Mackay,Male,35,Wales,Other,09.Oct.15,136365.52
2334,300002335,Benjamin,Howard,Male,36,Wales,White Collar,27.Sep.15,144209.77
3184,300003185,Piers,Dyer,Male,39,Wales,White Collar,14.Nov.15,144607.38
523,300000524,Brandon,Clark,Male,31,Wales,White Collar,16.May.15,145995.97

In [156]:
bank.sort_values(["Region","Balance"], ascending=[True,False])

,Customer ID,Name,Surname,Gender,Age,Region,Job Classification,Date Joined,Balance
1306,100001307,Dorothy,Jackson,Female,31,England,White Collar,22.Jul.15,183467.70
3449,100003450,Carl,Fraser,Male,35,England,White Collar,30.Nov.15,181680.99
3831,100003832,Sebastian,Arnold,Male,44,England,Blue Collar,20.Dec.15,161517.82
1822,100001823,Natalie,Paige,Female,34,England,White Collar,28.Aug.15,149684.40
3107,100003108,David,Metcalfe,Male,27,England,White Collar,11.Nov.15,146892.37
...,...,...,...,...,...,...,...,...,...
1464,300001465,Lily,Hart,Female,34,Wales,White Collar,31.Jul.15,1090.67
767,300000768,Tracey,Clark,Female,39,Wales,Other,31.May.15,747.35
686,300000687,Tim,Vance,Male,36,Wales,Other,26.May.15,401.13
3496,300003497,Rebecca,Howard,Female,30,Wales,Blue Collar,02.Dec.15,96.26
3467,300003468,Stewart,Johnston,Male,41,Wales,Blue Collar,30.Nov.15,77.46

In [160]:
# Fetch the data of top 5 balance maintaining customers from England
bank.loc[bank["Region"]=="England",:].sort_values("Balance",ascending=False).head()

,Customer ID,Name,Surname,Gender,Age,Region,Job Classification,Date Joined,Balance
1306,100001307,Dorothy,Jackson,Female,31,England,White Collar,22.Jul.15,183467.70
3449,100003450,Carl,Fraser,Male,35,England,White Collar,30.Nov.15,181680.99
3831,100003832,Sebastian,Arnold,Male,44,England,Blue Collar,20.Dec.15,161517.82
1822,100001823,Natalie,Paige,Female,34,England,White Collar,28.Aug.15,149684.40
3107,100003108,David,Metcalfe,Male,27,England,White Collar,11.Nov.15,146892.37

In [161]:
# Add a new column in dataframe
bank["Interest"]=bank["Balance"]*0.1

In [162]:
bank

,Customer ID,Name,Surname,Gender,Age,Region,Job Classification,Date Joined,Balance,Interest
0,100000001,Simon,Walsh,Male,21,England,White Collar,05.Jan.15,113810.15,11381.015
1,400000002,Jasmine,Miller,Female,34,Northern Ireland,Blue Collar,06.Jan.15,36919.73,3691.973
2,100000003,Liam,Brown,Male,46,England,White Collar,07.Jan.15,101536.83,10153.683
3,300000004,Trevor,Parr,Male,32,Wales,White Collar,08.Jan.15,1421.52,142.152
4,100000005,Deirdre,Pullman,Female,38,England,Blue Collar,09.Jan.15,35639.79,3563.979
...,...,...,...,...,...,...,...,...,...,...
4009,200004010,Sam,Lewis,Male,64,Scotland,Other,30.Dec.15,19711.66,1971.166
4010,200004011,Keith,Hughes,Male,52,Scotland,Blue Collar,30.Dec.15,56069.72,5606.972
4011,200004012,Hannah,Springer,Female,50,Scotland,Other,30.Dec.15,59477.82,5947.782
4012,200004013,Christian,Reid,Male,51,Scotland,Blue Collar,30.Dec.15,239.45,23.945
4013,300004014,Stephen,May,Male,33,Wales,Blue Collar,30.Dec.15,30293.19,3029.319

In [164]:
bank.to_csv("bank_interest.csv")

In [165]:
# Drop a column for row or column 
# axis=0 if row
# axis=1 if column
bank.drop("Interest",axis=1, inplace=True)

In [166]:
bank

,Customer ID,Name,Surname,Gender,Age,Region,Job Classification,Date Joined,Balance
0,100000001,Simon,Walsh,Male,21,England,White Collar,05.Jan.15,113810.15
1,400000002,Jasmine,Miller,Female,34,Northern Ireland,Blue Collar,06.Jan.15,36919.73
2,100000003,Liam,Brown,Male,46,England,White Collar,07.Jan.15,101536.83
3,300000004,Trevor,Parr,Male,32,Wales,White Collar,08.Jan.15,1421.52
4,100000005,Deirdre,Pullman,Female,38,England,Blue Collar,09.Jan.15,35639.79
...,...,...,...,...,...,...,...,...,...
4009,200004010,Sam,Lewis,Male,64,Scotland,Other,30.Dec.15,19711.66
4010,200004011,Keith,Hughes,Male,52,Scotland,Blue Collar,30.Dec.15,56069.72
4011,200004012,Hannah,Springer,Female,50,Scotland,Other,30.Dec.15,59477.82
4012,200004013,Christian,Reid,Male,51,Scotland,Blue Collar,30.Dec.15,239.45
4013,300004014,Stephen,May,Male,33,Wales,Blue Collar,30.Dec.15,30293.19

In [167]:
# Remove the blank rows
bank.dropna(inplace=True)

In [168]:
bank=bank.loc[bank.Region!="England"]

In [169]:
# add the column of interest -- balance>100000 --10%
# Balance 50000-1L --8%
# <50000 ---6%
def interest(b):
    if b>100000:
        return 0.1*b
    elif b>=50000 and b<=100000:
        return b*0.08
    else:
        return b*0.06

In [170]:
bank["Interest"] = bank["Balance"].apply(interest)

C:\Users\Administrator\AppData\Local\Temp\2\ipykernel_5336\1309627734.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bank["Interest"] = bank["Balance"].apply(interest)

In [171]:
bank

,Customer ID,Name,Surname,Gender,Age,Region,Job Classification,Date Joined,Balance,Interest
1,400000002,Jasmine,Miller,Female,34,Northern Ireland,Blue Collar,06.Jan.15,36919.73,2215.1838
3,300000004,Trevor,Parr,Male,32,Wales,White Collar,08.Jan.15,1421.52,85.2912
5,300000006,Ava,Coleman,Female,30,Wales,Blue Collar,09.Jan.15,122443.77,12244.3770
7,200000008,Lisa,Knox,Female,48,Scotland,Other,11.Jan.15,36680.17,2200.8102
8,300000009,Ruth,Campbell,Female,33,Wales,White Collar,11.Jan.15,74284.35,5942.7480
...,...,...,...,...,...,...,...,...,...,...
4009,200004010,Sam,Lewis,Male,64,Scotland,Other,30.Dec.15,19711.66,1182.6996
4010,200004011,Keith,Hughes,Male,52,Scotland,Blue Collar,30.Dec.15,56069.72,4485.5776
4011,200004012,Hannah,Springer,Female,50,Scotland,Other,30.Dec.15,59477.82,4758.2256
4012,200004013,Christian,Reid,Male,51,Scotland,Blue Collar,30.Dec.15,239.45,14.3670
4013,300004014,Stephen,May,Male,33,Wales,Blue Collar,30.Dec.15,30293.19,1817.5914

In [172]:
# introduce some null values
bank.loc[bank.Age>60,"Age"]=np.nan

In [173]:
bank

,Customer ID,Name,Surname,Gender,Age,Region,Job Classification,Date Joined,Balance,Interest
1,400000002,Jasmine,Miller,Female,34.0,Northern Ireland,Blue Collar,06.Jan.15,36919.73,2215.1838
3,300000004,Trevor,Parr,Male,32.0,Wales,White Collar,08.Jan.15,1421.52,85.2912
5,300000006,Ava,Coleman,Female,30.0,Wales,Blue Collar,09.Jan.15,122443.77,12244.3770
7,200000008,Lisa,Knox,Female,48.0,Scotland,Other,11.Jan.15,36680.17,2200.8102
8,300000009,Ruth,Campbell,Female,33.0,Wales,White Collar,11.Jan.15,74284.35,5942.7480
...,...,...,...,...,...,...,...,...,...,...
4009,200004010,Sam,Lewis,Male,NaN,Scotland,Other,30.Dec.15,19711.66,1182.6996
4010,200004011,Keith,Hughes,Male,52.0,Scotland,Blue Collar,30.Dec.15,56069.72,4485.5776
4011,200004012,Hannah,Springer,Female,50.0,Scotland,Other,30.Dec.15,59477.82,4758.2256
4012,200004013,Christian,Reid,Male,51.0,Scotland,Blue Collar,30.Dec.15,239.45,14.3670
4013,300004014,Stephen,May,Male,33.0,Wales,Blue Collar,30.Dec.15,30293.19,1817.5914

In [174]:
bank.count()

Customer ID           1855
Name                  1855
Surname               1855
Gender                1855
Age                   1789
Region                1855
Job Classification    1855
Date Joined           1855
Balance               1855
Interest              1855
dtype: int64

In [177]:
# % of missing values in each column
round((1-bank.count()/bank.shape[0])*100,2)

Customer ID           0.00
Name                  0.00
Surname               0.00
Gender                0.00
Age                   3.56
Region                0.00
Job Classification    0.00
Date Joined           0.00
Balance               0.00
Interest              0.00
dtype: float64

In [179]:
bank.loc[bank.Age.isna(),:]
bank.loc[bank.Age.notna(),:]

,Customer ID,Name,Surname,Gender,Age,Region,Job Classification,Date Joined,Balance,Interest
1,400000002,Jasmine,Miller,Female,34.0,Northern Ireland,Blue Collar,06.Jan.15,36919.73,2215.1838
3,300000004,Trevor,Parr,Male,32.0,Wales,White Collar,08.Jan.15,1421.52,85.2912
5,300000006,Ava,Coleman,Female,30.0,Wales,Blue Collar,09.Jan.15,122443.77,12244.3770
7,200000008,Lisa,Knox,Female,48.0,Scotland,Other,11.Jan.15,36680.17,2200.8102
8,300000009,Ruth,Campbell,Female,33.0,Wales,White Collar,11.Jan.15,74284.35,5942.7480
...,...,...,...,...,...,...,...,...,...,...
4001,300004002,Austin,Paterson,Male,30.0,Wales,White Collar,29.Dec.15,8250.75,495.0450
4010,200004011,Keith,Hughes,Male,52.0,Scotland,Blue Collar,30.Dec.15,56069.72,4485.5776
4011,200004012,Hannah,Springer,Female,50.0,Scotland,Other,30.Dec.15,59477.82,4758.2256
4012,200004013,Christian,Reid,Male,51.0,Scotland,Blue Collar,30.Dec.15,239.45,14.3670
4013,300004014,Stephen,May,Male,33.0,Wales,Blue Collar,30.Dec.15,30293.19,1817.5914

In [180]:
bank.Age.mean()

np.float64(42.35606484069312)

In [181]:
# Age is null where put avg age
# in the numpy lib we have where
bank["Age"] = np.where(bank.Age.isna(), bank.Age.mean(), bank.Age)

C:\Users\Administrator\AppData\Local\Temp\2\ipykernel_5336\116453386.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bank["Age"] = np.where(bank.Age.isna(), bank.Age.mean(), bank.Age)

In [182]:
bank

,Customer ID,Name,Surname,Gender,Age,Region,Job Classification,Date Joined,Balance,Interest
1,400000002,Jasmine,Miller,Female,34.000000,Northern Ireland,Blue Collar,06.Jan.15,36919.73,2215.1838
3,300000004,Trevor,Parr,Male,32.000000,Wales,White Collar,08.Jan.15,1421.52,85.2912
5,300000006,Ava,Coleman,Female,30.000000,Wales,Blue Collar,09.Jan.15,122443.77,12244.3770
7,200000008,Lisa,Knox,Female,48.000000,Scotland,Other,11.Jan.15,36680.17,2200.8102
8,300000009,Ruth,Campbell,Female,33.000000,Wales,White Collar,11.Jan.15,74284.35,5942.7480
...,...,...,...,...,...,...,...,...,...,...
4009,200004010,Sam,Lewis,Male,42.356065,Scotland,Other,30.Dec.15,19711.66,1182.6996
4010,200004011,Keith,Hughes,Male,52.000000,Scotland,Blue Collar,30.Dec.15,56069.72,4485.5776
4011,200004012,Hannah,Springer,Female,50.000000,Scotland,Other,30.Dec.15,59477.82,4758.2256
4012,200004013,Christian,Reid,Male,51.000000,Scotland,Blue Collar,30.Dec.15,239.45,14.3670
4013,300004014,Stephen,May,Male,33.000000,Wales,Blue Collar,30.Dec.15,30293.19,1817.5914

In [183]:
# unique
bank.Region.unique()

array(['Northern Ireland', 'Wales', 'Scotland'], dtype=object)

In [184]:
bank.Region.nunique()

3