In [1]:
# JSON
# Javascript Object Notation
# JSON
# You want to convert json to a python object
# You want to convert python object to json
import json

In [2]:
# json.dumps --> convert the python object to JSON string
# json.Loads --> convert JSON string to python object
# json.dump --> Write the python object to json file
# json.Load --> read the json data from a file

In [7]:
employee={
    "ID":1,
    "name":"Sam",
    "salary":10000
}

In [8]:
type(employee)

dict

In [4]:
json_data=json.dumps(employee)

In [5]:
type(json_data)

str

In [6]:
print(json_data)

{"ID": 1, "name": "Sam", "salary": 10000}

In [12]:
# Pretty Printing
employee={
    "ID":1,
    "name":"Sam",
    "salary":10000,
    "country":"US"
}

In [13]:
print(json.dumps(employee, indent=4))

{
    "ID": 1,
    "name": "Sam",
    "salary": 10000,
    "country": "US"
}

In [15]:
# Sort the keys
print(json.dumps(employee, indent=4, sort_keys=True))

{
    "ID": 1,
    "country": "US",
    "name": "Sam",
    "salary": 10000
}

In [16]:
# json.loads --> JSON string to python object
json_data = '{"ID":101, "name":"Sam", "salary":10000}'

In [17]:
type(json_data)

str

In [18]:
employee=json.loads(json_data)

In [19]:
type(employee)

dict

In [20]:
employee["ID"]

101

In [21]:
# json.dump --> Write the python object to a JSON file
employee={
    "ID":1,
    "name":"Sam",
    "salary":10000,
    "country":"US"
}

In [22]:
# open the file
# r, w, a
# close the file

In [23]:
with open("employee.json", "w") as file:
    json.dump(employee, file, indent=4)

In [24]:
# Read the data from this json file into a python object
with open("employee.json", "r") as file:
    data=json.load(file)

In [25]:
type(data)

dict

In [26]:
import requests

In [27]:
response = requests.get("https://jsonplaceholder.typicode.com/users")

In [29]:
response

In [30]:
users = response.json()

In [31]:
print(users)

[{'id': 1, 'name': 'Leanne Graham', 'username': 'Bret', 'email': 'Sincere@april.biz', 'address': {'street': 'Kulas Light', 'suite': 'Apt. 556', 'city': 'Gwenborough', 'zipcode': '92998-3874', 'geo': {'lat': '-37.3159', 'lng': '81.1496'}}, 'phone': '1-770-736-8031 x56442', 'website': 'hildegard.org', 'company': {'name': 'Romaguera-Crona', 'catchPhrase': 'Multi-layered client-server neural-net', 'bs': 'harness real-time e-markets'}}, {'id': 2, 'name': 'Ervin Howell', 'username': 'Antonette', 'email': 'Shanna@melissa.tv', 'address': {'street': 'Victor Plains', 'suite': 'Suite 879', 'city': 'Wisokyburgh', 'zipcode': '90566-7771', 'geo': {'lat': '-43.9509', 'lng': '-34.4618'}}, 'phone': '010-692-6593 x09125', 'website': 'anastasia.net', 'company': {'name': 'Deckow-Crist', 'catchPhrase': 'Proactive didactic contingency', 'bs': 'synergize scalable supply-chains'}}, {'id': 3, 'name': 'Clementine Bauch', 'username': 'Samantha', 'email': 'Nathan@yesenia.net', 'address': {'street': 'Douglas Extension', 'suite': 'Suite 847', 'city': 'McKenziehaven', 'zipcode': '59590-4157', 'geo': {'lat': '-68.6102', 'lng': '-47.0653'}}, 'phone': '1-463-123-4447', 'website': 'ramiro.info', 'company': {'name': 'Romaguera-Jacobson', 'catchPhrase': 'Face to face bifurcated interface', 'bs': 'e-enable strategic applications'}}, {'id': 4, 'name': 'Patricia Lebsack', 'username': 'Karianne', 'email': 'Julianne.OConner@kory.org', 'address': {'street': 'Hoeger Mall', 'suite': 'Apt. 692', 'city': 'South Elvis', 'zipcode': '53919-4257', 'geo': {'lat': '29.4572', 'lng': '-164.2990'}}, 'phone': '493-170-9623 x156', 'website': 'kale.biz', 'company': {'name': 'Robel-Corkery', 'catchPhrase': 'Multi-tiered zero tolerance productivity', 'bs': 'transition cutting-edge web services'}}, {'id': 5, 'name': 'Chelsey Dietrich', 'username': 'Kamren', 'email': 'Lucio_Hettinger@annie.ca', 'address': {'street': 'Skiles Walks', 'suite': 'Suite 351', 'city': 'Roscoeview', 'zipcode': '33263', 'geo': {'lat': '-31.8129', 'lng': '62.5342'}}, 'phone': '(254)954-1289', 'website': 'demarco.info', 'company': {'name': 'Keebler LLC', 'catchPhrase': 'User-centric fault-tolerant solution', 'bs': 'revolutionize end-to-end systems'}}, {'id': 6, 'name': 'Mrs. Dennis Schulist', 'username': 'Leopoldo_Corkery', 'email': 'Karley_Dach@jasper.info', 'address': {'street': 'Norberto Crossing', 'suite': 'Apt. 950', 'city': 'South Christy', 'zipcode': '23505-1337', 'geo': {'lat': '-71.4197', 'lng': '71.7478'}}, 'phone': '1-477-935-8478 x6430', 'website': 'ola.org', 'company': {'name': 'Considine-Lockman', 'catchPhrase': 'Synchronised bottom-line interface', 'bs': 'e-enable innovative applications'}}, {'id': 7, 'name': 'Kurtis Weissnat', 'username': 'Elwyn.Skiles', 'email': 'Telly.Hoeger@billy.biz', 'address': {'street': 'Rex Trail', 'suite': 'Suite 280', 'city': 'Howemouth', 'zipcode': '58804-1099', 'geo': {'lat': '24.8918', 'lng': '21.8984'}}, 'phone': '210.067.6132', 'website': 'elvis.io', 'company': {'name': 'Johns Group', 'catchPhrase': 'Configurable multimedia task-force', 'bs': 'generate enterprise e-tailers'}}, {'id': 8, 'name': 'Nicholas Runolfsdottir V', 'username': 'Maxime_Nienow', 'email': 'Sherwood@rosamond.me', 'address': {'street': 'Ellsworth Summit', 'suite': 'Suite 729', 'city': 'Aliyaview', 'zipcode': '45169', 'geo': {'lat': '-14.3990', 'lng': '-120.7677'}}, 'phone': '586.493.6943 x140', 'website': 'jacynthe.com', 'company': {'name': 'Abernathy Group', 'catchPhrase': 'Implemented secondary concept', 'bs': 'e-enable extensible e-tailers'}}, {'id': 9, 'name': 'Glenna Reichert', 'username': 'Delphine', 'email': 'Chaim_McDermott@dana.io', 'address': {'street': 'Dayna Park', 'suite': 'Suite 449', 'city': 'Bartholomebury', 'zipcode': '76495-3109', 'geo': {'lat': '24.6463', 'lng': '-168.8889'}}, 'phone': '(775)976-6794 x41206', 'website': 'conrad.com', 'company': {'name': 'Yost and Sons', 'catchPhrase': 'Switchable contextually-based project', 'bs': 'aggregate real-time technologies'}}, {'id': 10, 'name': 'Clementina DuBuque', 'username': 'Moriah.Stanton', 'email': 'Rey.Padberg@karina.biz', 'address': {'street': 'Kattie Turnpike', 'suite': 'Suite 198', 'city': 'Lebsackbury', 'zipcode': '31428-2261', 'geo': {'lat': '-38.2386', 'lng': '57.2232'}}, 'phone': '024-648-3804', 'website': 'ambrose.net', 'company': {'name': 'Hoeger LLC', 'catchPhrase': 'Centralized empowering task-force', 'bs': 'target end-to-end models'}}]

In [34]:
# Get the list of all user names
out=[]
for i in users:
    out.append(i["name"])

In [35]:
out

['Leanne Graham',
 'Ervin Howell',
 'Clementine Bauch',
 'Patricia Lebsack',
 'Chelsey Dietrich',
 'Mrs. Dennis Schulist',
 'Kurtis Weissnat',
 'Nicholas Runolfsdottir V',
 'Glenna Reichert',
 'Clementina DuBuque']

In [40]:
url = "https://swapi.py4e.com/api/people/"
response = requests.get(url)

if response.status_code==200:
    data=response.json()

    print("Total Characters: ", data["count"])
    print()
else:
    print("Failed to fetch the data")

Total Characters:  87

In [45]:
# Print the name, height, and gender, mass
url = "https://swapi.py4e.com/api/people/"
response = requests.get(url)

if response.status_code==200:
    data=response.json()

    print("Total Characters: ", data["count"])
    print()
    for person in data["results"]:
        print("Name", person["name"])
        print("Height", person["height"])
        print("Gender", person["gender"])
        print("Mass", person["mass"])
        print("------------------------")
else:
    print("Failed to fetch the data")

Total Characters:  87

Name Luke Skywalker
Height 172
Gender male
Mass 77
------------------------
Name C-3PO
Height 167
Gender n/a
Mass 75
------------------------
Name R2-D2
Height 96
Gender n/a
Mass 32
------------------------
Name Darth Vader
Height 202
Gender male
Mass 136
------------------------
Name Leia Organa
Height 150
Gender female
Mass 49
------------------------
Name Owen Lars
Height 178
Gender male
Mass 120
------------------------
Name Beru Whitesun lars
Height 165
Gender female
Mass 75
------------------------
Name R5-D4
Height 97
Gender n/a
Mass 32
------------------------
Name Biggs Darklighter
Height 183
Gender male
Mass 84
------------------------
Name Obi-Wan Kenobi
Height 182
Gender male
Mass 77
------------------------

In [41]:
print(response)

<Response [200]>

In [43]:
# response code is 200 --> python was successfully able to connect to API
type(data)

dict

In [44]:
data

{'count': 87,
 'next': 'https://swapi.py4e.com/api/people/?page=2',
 'previous': None,
 'results': [{'name': 'Luke Skywalker',
   'height': '172',
   'mass': '77',
   'hair_color': 'blond',
   'skin_color': 'fair',
   'eye_color': 'blue',
   'birth_year': '19BBY',
   'gender': 'male',
   'homeworld': 'https://swapi.py4e.com/api/planets/1/',
   'films': ['https://swapi.py4e.com/api/films/1/',
    'https://swapi.py4e.com/api/films/2/',
    'https://swapi.py4e.com/api/films/3/',
    'https://swapi.py4e.com/api/films/6/',
    'https://swapi.py4e.com/api/films/7/'],
   'species': ['https://swapi.py4e.com/api/species/1/'],
   'vehicles': ['https://swapi.py4e.com/api/vehicles/14/',
    'https://swapi.py4e.com/api/vehicles/30/'],
   'starships': ['https://swapi.py4e.com/api/starships/12/',
    'https://swapi.py4e.com/api/starships/22/'],
   'created': '2014-12-09T13:50:51.644000Z',
   'edited': '2014-12-20T21:17:56.891000Z',
   'url': 'https://swapi.py4e.com/api/people/1/'},
  {'name': 'C-3PO',
   'height': '167',
   'mass': '75',
   'hair_color': 'n/a',
   'skin_color': 'gold',
   'eye_color': 'yellow',
   'birth_year': '112BBY',
   'gender': 'n/a',
   'homeworld': 'https://swapi.py4e.com/api/planets/1/',
   'films': ['https://swapi.py4e.com/api/films/1/',
    'https://swapi.py4e.com/api/films/2/',
    'https://swapi.py4e.com/api/films/3/',
    'https://swapi.py4e.com/api/films/4/',
    'https://swapi.py4e.com/api/films/5/',
    'https://swapi.py4e.com/api/films/6/'],
   'species': ['https://swapi.py4e.com/api/species/2/'],
   'vehicles': [],
   'starships': [],
   'created': '2014-12-10T15:10:51.357000Z',
   'edited': '2014-12-20T21:17:50.309000Z',
   'url': 'https://swapi.py4e.com/api/people/2/'},
  {'name': 'R2-D2',
   'height': '96',
   'mass': '32',
   'hair_color': 'n/a',
   'skin_color': 'white, blue',
   'eye_color': 'red',
   'birth_year': '33BBY',
   'gender': 'n/a',
   'homeworld': 'https://swapi.py4e.com/api/planets/8/',
   'films': ['https://swapi.py4e.com/api/films/1/',
    'https://swapi.py4e.com/api/films/2/',
    'https://swapi.py4e.com/api/films/3/',
    'https://swapi.py4e.com/api/films/4/',
    'https://swapi.py4e.com/api/films/5/',
    'https://swapi.py4e.com/api/films/6/',
    'https://swapi.py4e.com/api/films/7/'],
   'species': ['https://swapi.py4e.com/api/species/2/'],
   'vehicles': [],
   'starships': [],
   'created': '2014-12-10T15:11:50.376000Z',
   'edited': '2014-12-20T21:17:50.311000Z',
   'url': 'https://swapi.py4e.com/api/people/3/'},
  {'name': 'Darth Vader',
   'height': '202',
   'mass': '136',
   'hair_color': 'none',
   'skin_color': 'white',
   'eye_color': 'yellow',
   'birth_year': '41.9BBY',
   'gender': 'male',
   'homeworld': 'https://swapi.py4e.com/api/planets/1/',
   'films': ['https://swapi.py4e.com/api/films/1/',
    'https://swapi.py4e.com/api/films/2/',
    'https://swapi.py4e.com/api/films/3/',
    'https://swapi.py4e.com/api/films/6/'],
   'species': ['https://swapi.py4e.com/api/species/1/'],
   'vehicles': [],
   'starships': ['https://swapi.py4e.com/api/starships/13/'],
   'created': '2014-12-10T15:18:20.704000Z',
   'edited': '2014-12-20T21:17:50.313000Z',
   'url': 'https://swapi.py4e.com/api/people/4/'},
  {'name': 'Leia Organa',
   'height': '150',
   'mass': '49',
   'hair_color': 'brown',
   'skin_color': 'light',
   'eye_color': 'brown',
   'birth_year': '19BBY',
   'gender': 'female',
   'homeworld': 'https://swapi.py4e.com/api/planets/2/',
   'films': ['https://swapi.py4e.com/api/films/1/',
    'https://swapi.py4e.com/api/films/2/',
    'https://swapi.py4e.com/api/films/3/',
    'https://swapi.py4e.com/api/films/6/',
    'https://swapi.py4e.com/api/films/7/'],
   'species': ['https://swapi.py4e.com/api/species/1/'],
   'vehicles': ['https://swapi.py4e.com/api/vehicles/30/'],
   'starships': [],
   'created': '2014-12-10T15:20:09.791000Z',
   'edited': '2014-12-20T21:17:50.315000Z',
   'url': 'https://swapi.py4e.com/api/people/5/'},
  {'name': 'Owen Lars',
   'height': '178',
   'mass': '120',
   'hair_color': 'brown, grey',
   'skin_color': 'light',
   'eye_color': 'blue',
   'birth_year': '52BBY',
   'gender': 'male',
   'homeworld': 'https://swapi.py4e.com/api/planets/1/',
   'films': ['https://swapi.py4e.com/api/films/1/',
    'https://swapi.py4e.com/api/films/5/',
    'https://swapi.py4e.com/api/films/6/'],
   'species': ['https://swapi.py4e.com/api/species/1/'],
   'vehicles': [],
   'starships': [],
   'created': '2014-12-10T15:52:14.024000Z',
   'edited': '2014-12-20T21:17:50.317000Z',
   'url': 'https://swapi.py4e.com/api/people/6/'},
  {'name': 'Beru Whitesun lars',
   'height': '165',
   'mass': '75',
   'hair_color': 'brown',
   'skin_color': 'light',
   'eye_color': 'blue',
   'birth_year': '47BBY',
   'gender': 'female',
   'homeworld': 'https://swapi.py4e.com/api/planets/1/',
   'films': ['https://swapi.py4e.com/api/films/1/',
    'https://swapi.py4e.com/api/films/5/',
    'https://swapi.py4e.com/api/films/6/'],
   'species': ['https://swapi.py4e.com/api/species/1/'],
   'vehicles': [],
   'starships': [],
   'created': '2014-12-10T15:53:41.121000Z',
   'edited': '2014-12-20T21:17:50.319000Z',
   'url': 'https://swapi.py4e.com/api/people/7/'},
  {'name': 'R5-D4',
   'height': '97',
   'mass': '32',
   'hair_color': 'n/a',
   'skin_color': 'white, red',
   'eye_color': 'red',
   'birth_year': 'unknown',
   'gender': 'n/a',
   'homeworld': 'https://swapi.py4e.com/api/planets/1/',
   'films': ['https://swapi.py4e.com/api/films/1/'],
   'species': ['https://swapi.py4e.com/api/species/2/'],
   'vehicles': [],
   'starships': [],
   'created': '2014-12-10T15:57:50.959000Z',
   'edited': '2014-12-20T21:17:50.321000Z',
   'url': 'https://swapi.py4e.com/api/people/8/'},
  {'name': 'Biggs Darklighter',
   'height': '183',
   'mass': '84',
   'hair_color': 'black',
   'skin_color': 'light',
   'eye_color': 'brown',
   'birth_year': '24BBY',
   'gender': 'male',
   'homeworld': 'https://swapi.py4e.com/api/planets/1/',
   'films': ['https://swapi.py4e.com/api/films/1/'],
   'species': ['https://swapi.py4e.com/api/species/1/'],
   'vehicles': [],
   'starships': ['https://swapi.py4e.com/api/starships/12/'],
   'created': '2014-12-10T15:59:50.509000Z',
   'edited': '2014-12-20T21:17:50.323000Z',
   'url': 'https://swapi.py4e.com/api/people/9/'},
  {'name': 'Obi-Wan Kenobi',
   'height': '182',
   'mass': '77',
   'hair_color': 'auburn, white',
   'skin_color': 'fair',
   'eye_color': 'blue-gray',
   'birth_year': '57BBY',
   'gender': 'male',
   'homeworld': 'https://swapi.py4e.com/api/planets/20/',
   'films': ['https://swapi.py4e.com/api/films/1/',
    'https://swapi.py4e.com/api/films/2/',
    'https://swapi.py4e.com/api/films/3/',
    'https://swapi.py4e.com/api/films/4/',
    'https://swapi.py4e.com/api/films/5/',
    'https://swapi.py4e.com/api/films/6/'],
   'species': ['https://swapi.py4e.com/api/species/1/'],
   'vehicles': ['https://swapi.py4e.com/api/vehicles/38/'],
   'starships': ['https://swapi.py4e.com/api/starships/48/',
    'https://swapi.py4e.com/api/starships/59/',
    'https://swapi.py4e.com/api/starships/64/',
    'https://swapi.py4e.com/api/starships/65/',
    'https://swapi.py4e.com/api/starships/74/'],
   'created': '2014-12-10T16:16:29.192000Z',
   'edited': '2014-12-20T21:17:50.325000Z',
   'url': 'https://swapi.py4e.com/api/people/10/'}]}

In [46]:
# Saving data in dataframe
import pandas as pd
url = "https://swapi.py4e.com/api/people/"
response = requests.get(url)

if response.status_code==200:
    data=response.json()
    df=pd.DataFrame(data["results"])
else:
    print("Failed to fetch the data")

df.to_csv("starwarsapidata.csv")

In [47]:
df

,name,height,mass,hair_color,skin_color,eye_color,birth_year,gender,homeworld,films,species,vehicles,starships,created,edited,url
0,Luke Skywalker,172,77,blond,fair,blue,19BBY,male,https://swapi.py4e.com/api/planets/1/,"[https://swapi.py4e.com/api/films/1/, https://...",[https://swapi.py4e.com/api/species/1/],"[https://swapi.py4e.com/api/vehicles/14/, http...","[https://swapi.py4e.com/api/starships/12/, htt...",2014-12-09T13:50:51.644000Z,2014-12-20T21:17:56.891000Z,https://swapi.py4e.com/api/people/1/
1,C-3PO,167,75,n/a,gold,yellow,112BBY,n/a,https://swapi.py4e.com/api/planets/1/,"[https://swapi.py4e.com/api/films/1/, https://...",[https://swapi.py4e.com/api/species/2/],[],[],2014-12-10T15:10:51.357000Z,2014-12-20T21:17:50.309000Z,https://swapi.py4e.com/api/people/2/
2,R2-D2,96,32,n/a,"white, blue",red,33BBY,n/a,https://swapi.py4e.com/api/planets/8/,"[https://swapi.py4e.com/api/films/1/, https://...",[https://swapi.py4e.com/api/species/2/],[],[],2014-12-10T15:11:50.376000Z,2014-12-20T21:17:50.311000Z,https://swapi.py4e.com/api/people/3/
3,Darth Vader,202,136,none,white,yellow,41.9BBY,male,https://swapi.py4e.com/api/planets/1/,"[https://swapi.py4e.com/api/films/1/, https://...",[https://swapi.py4e.com/api/species/1/],[],[https://swapi.py4e.com/api/starships/13/],2014-12-10T15:18:20.704000Z,2014-12-20T21:17:50.313000Z,https://swapi.py4e.com/api/people/4/
4,Leia Organa,150,49,brown,light,brown,19BBY,female,https://swapi.py4e.com/api/planets/2/,"[https://swapi.py4e.com/api/films/1/, https://...",[https://swapi.py4e.com/api/species/1/],[https://swapi.py4e.com/api/vehicles/30/],[],2014-12-10T15:20:09.791000Z,2014-12-20T21:17:50.315000Z,https://swapi.py4e.com/api/people/5/
5,Owen Lars,178,120,"brown, grey",light,blue,52BBY,male,https://swapi.py4e.com/api/planets/1/,"[https://swapi.py4e.com/api/films/1/, https://...",[https://swapi.py4e.com/api/species/1/],[],[],2014-12-10T15:52:14.024000Z,2014-12-20T21:17:50.317000Z,https://swapi.py4e.com/api/people/6/
6,Beru Whitesun lars,165,75,brown,light,blue,47BBY,female,https://swapi.py4e.com/api/planets/1/,"[https://swapi.py4e.com/api/films/1/, https://...",[https://swapi.py4e.com/api/species/1/],[],[],2014-12-10T15:53:41.121000Z,2014-12-20T21:17:50.319000Z,https://swapi.py4e.com/api/people/7/
7,R5-D4,97,32,n/a,"white, red",red,unknown,n/a,https://swapi.py4e.com/api/planets/1/,[https://swapi.py4e.com/api/films/1/],[https://swapi.py4e.com/api/species/2/],[],[],2014-12-10T15:57:50.959000Z,2014-12-20T21:17:50.321000Z,https://swapi.py4e.com/api/people/8/
8,Biggs Darklighter,183,84,black,light,brown,24BBY,male,https://swapi.py4e.com/api/planets/1/,[https://swapi.py4e.com/api/films/1/],[https://swapi.py4e.com/api/species/1/],[],[https://swapi.py4e.com/api/starships/12/],2014-12-10T15:59:50.509000Z,2014-12-20T21:17:50.323000Z,https://swapi.py4e.com/api/people/9/
9,Obi-Wan Kenobi,182,77,"auburn, white",fair,blue-gray,57BBY,male,https://swapi.py4e.com/api/planets/20/,"[https://swapi.py4e.com/api/films/1/, https://...",[https://swapi.py4e.com/api/species/1/],[https://swapi.py4e.com/api/vehicles/38/],"[https://swapi.py4e.com/api/starships/48/, htt...",2014-12-10T16:16:29.192000Z,2014-12-20T21:17:50.325000Z,https://swapi.py4e.com/api/people/10/

In [ ]:
# Open AI
from openai import OpenAI
client = OpenAI(api_key="api_key_")
response = client.response.create(
    model="gpt-5.5",
    input="Tell me about Machine Learning"
)

print(response.output_text)

In [48]:
pip install openai

Collecting openai
  Downloading openai-2.50.0-py3-none-any.whl.metadata (36 kB)
Requirement already satisfied: anyio<5,>=3.5.0 in c:\tools\anaconda3\lib\site-packages (from openai) (4.10.0)
Requirement already satisfied: distro<2,>=1.7.0 in c:\tools\anaconda3\lib\site-packages (from openai) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\tools\anaconda3\lib\site-packages (from openai) (0.28.1)
Collecting jiter<1,>=0.10.0 (from openai)
  Downloading jiter-0.16.0-cp313-cp313-win_amd64.whl.metadata (5.3 kB)
Requirement already satisfied: pydantic<3,>=1.9.0 in c:\tools\anaconda3\lib\site-packages (from openai) (2.12.4)
Requirement already satisfied: sniffio in c:\tools\anaconda3\lib\site-packages (from openai) (1.3.0)
Requirement already satisfied: tqdm>4 in c:\tools\anaconda3\lib\site-packages (from openai) (4.67.1)
Requirement already satisfied: typing-extensions<5,>=4.14 in c:\tools\anaconda3\lib\site-packages (from openai) (4.15.0)
Requirement already satisfied: idna>=2.8 in c:\tools\anaconda3\lib\site-packages (from anyio<5,>=3.5.0->openai) (3.11)
Requirement already satisfied: certifi in c:\tools\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->openai) (2025.11.12)
Requirement already satisfied: httpcore==1.* in c:\tools\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->openai) (1.0.9)
Requirement already satisfied: h11>=0.16 in c:\tools\anaconda3\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in c:\tools\anaconda3\lib\site-packages (from pydantic<3,>=1.9.0->openai) (0.6.0)
Requirement already satisfied: pydantic-core==2.41.5 in c:\tools\anaconda3\lib\site-packages (from pydantic<3,>=1.9.0->openai) (2.41.5)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\tools\anaconda3\lib\site-packages (from pydantic<3,>=1.9.0->openai) (0.4.2)
Requirement already satisfied: colorama in c:\tools\anaconda3\lib\site-packages (from tqdm>4->openai) (0.4.6)
Downloading openai-2.50.0-py3-none-any.whl (1.7 MB)
   ---------------------------------------- 0.0/1.7 MB ? eta -:--:--
   ---------------------------------------- 1.7/1.7 MB 11.2 MB/s  0:00:00
Downloading jiter-0.16.0-cp313-cp313-win_amd64.whl (196 kB)
Installing collected packages: jiter, openai

   -------------------- ------------------- 1/2 [openai]
   -------------------- ------------------- 1/2 [openai]
   -------------------- ------------------- 1/2 [openai]
   -------------------- ------------------- 1/2 [openai]
   -------------------- ------------------- 1/2 [openai]
   -------------------- ------------------- 1/2 [openai]
   -------------------- ------------------- 1/2 [openai]
   -------------------- ------------------- 1/2 [openai]
   -------------------- ------------------- 1/2 [openai]
   -------------------- ------------------- 1/2 [openai]
   -------------------- ------------------- 1/2 [openai]
   -------------------- ------------------- 1/2 [openai]
   -------------------- ------------------- 1/2 [openai]
   -------------------- ------------------- 1/2 [openai]
   -------------------- ------------------- 1/2 [openai]
   -------------------- ------------------- 1/2 [openai]
   -------------------- ------------------- 1/2 [openai]
   -------------------- ------------------- 1/2 [openai]
   -------------------- ------------------- 1/2 [openai]
   -------------------- ------------------- 1/2 [openai]
   -------------------- ------------------- 1/2 [openai]
   -------------------- ------------------- 1/2 [openai]
   -------------------- ------------------- 1/2 [openai]
   -------------------- ------------------- 1/2 [openai]
   -------------------- ------------------- 1/2 [openai]
   -------------------- ------------------- 1/2 [openai]
   -------------------- ------------------- 1/2 [openai]
   -------------------- ------------------- 1/2 [openai]
   -------------------- ------------------- 1/2 [openai]
   -------------------- ------------------- 1/2 [openai]
   -------------------- ------------------- 1/2 [openai]
   -------------------- ------------------- 1/2 [openai]
   -------------------- ------------------- 1/2 [openai]
   -------------------- ------------------- 1/2 [openai]
   -------------------- ------------------- 1/2 [openai]
   -------------------- ------------------- 1/2 [openai]
   -------------------- ------------------- 1/2 [openai]
   -------------------- ------------------- 1/2 [openai]
   -------------------- ------------------- 1/2 [openai]
   -------------------- ------------------- 1/2 [openai]
   -------------------- ------------------- 1/2 [openai]
   -------------------- ------------------- 1/2 [openai]
   -------------------- ------------------- 1/2 [openai]
   -------------------- ------------------- 1/2 [openai]
   -------------------- ------------------- 1/2 [openai]
   -------------------- ------------------- 1/2 [openai]
   -------------------- ------------------- 1/2 [openai]
   -------------------- ------------------- 1/2 [openai]
   -------------------- ------------------- 1/2 [openai]
   -------------------- ------------------- 1/2 [openai]
   -------------------- ------------------- 1/2 [openai]
   -------------------- ------------------- 1/2 [openai]
   -------------------- ------------------- 1/2 [openai]
   -------------------- ------------------- 1/2 [openai]
   -------------------- ------------------- 1/2 [openai]
   -------------------- ------------------- 1/2 [openai]
   -------------------- ------------------- 1/2 [openai]
   -------------------- ------------------- 1/2 [openai]
   -------------------- ------------------- 1/2 [openai]
   -------------------- ------------------- 1/2 [openai]
   -------------------- ------------------- 1/2 [openai]
   -------------------- ------------------- 1/2 [openai]
   -------------------- ------------------- 1/2 [openai]
   -------------------- ------------------- 1/2 [openai]
   -------------------- ------------------- 1/2 [openai]
   -------------------- ------------------- 1/2 [openai]
   -------------------- ------------------- 1/2 [openai]
   -------------------- ------------------- 1/2 [openai]
   -------------------- ------------------- 1/2 [openai]
   -------------------- ------------------- 1/2 [openai]
   -------------------- ------------------- 1/2 [openai]
   -------------------- ------------------- 1/2 [openai]
   -------------------- ------------------- 1/2 [openai]
   -------------------- ------------------- 1/2 [openai]
   -------------------- ------------------- 1/2 [openai]
   -------------------- ------------------- 1/2 [openai]
   -------------------- ------------------- 1/2 [openai]
   -------------------- ------------------- 1/2 [openai]
   -------------------- ------------------- 1/2 [openai]
   -------------------- ------------------- 1/2 [openai]
   -------------------- ------------------- 1/2 [openai]
   -------------------- ------------------- 1/2 [openai]
   -------------------- ------------------- 1/2 [openai]
   -------------------- ------------------- 1/2 [openai]
   -------------------- ------------------- 1/2 [openai]
   -------------------- ------------------- 1/2 [openai]
   -------------------- ------------------- 1/2 [openai]
   -------------------- ------------------- 1/2 [openai]
   -------------------- ------------------- 1/2 [openai]
   -------------------- ------------------- 1/2 [openai]
   -------------------- ------------------- 1/2 [openai]
   -------------------- ------------------- 1/2 [openai]
   -------------------- ------------------- 1/2 [openai]
   -------------------- ------------------- 1/2 [openai]
   -------------------- ------------------- 1/2 [openai]
   -------------------- ------------------- 1/2 [openai]
   -------------------- ------------------- 1/2 [openai]
   -------------------- ------------------- 1/2 [openai]
   -------------------- ------------------- 1/2 [openai]
   ---------------------------------------- 2/2 [openai]

Successfully installed jiter-0.16.0 openai-2.50.0
Note: you may need to restart the kernel to use updated packages.

In [52]:
# boto3

# official AWS SDK...
# upload or download files from the S3 buckets

In [51]:
pip install boto3

Collecting boto3
  Downloading boto3-1.43.58-py3-none-any.whl.metadata (6.6 kB)
Collecting botocore<1.44.0,>=1.43.58 (from boto3)
  Downloading botocore-1.43.58-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in c:\tools\anaconda3\lib\site-packages (from boto3) (1.0.1)
Collecting s3transfer<0.20.0,>=0.19.0 (from boto3)
  Downloading s3transfer-0.19.2-py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in c:\tools\anaconda3\lib\site-packages (from botocore<1.44.0,>=1.43.58->boto3) (2.9.0.post0)
Requirement already satisfied: urllib3!=2.2.0,<3,>=1.25.4 in c:\tools\anaconda3\lib\site-packages (from botocore<1.44.0,>=1.43.58->boto3) (2.5.0)
Requirement already satisfied: six>=1.5 in c:\tools\anaconda3\lib\site-packages (from python-dateutil<3.0.0,>=2.1->botocore<1.44.0,>=1.43.58->boto3) (1.17.0)
Downloading boto3-1.43.58-py3-none-any.whl (140 kB)
Downloading botocore-1.43.58-py3-none-any.whl (15.4 MB)
   ---------------------------------------- 0.0/15.4 MB ? eta -:--:--
   ------------- -------------------------- 5.2/15.4 MB 29.0 MB/s eta 0:00:01
   ---------------------- ----------------- 8.7/15.4 MB 23.3 MB/s eta 0:00:01
   --------------------------- ------------ 10.5/15.4 MB 18.7 MB/s eta 0:00:01
   ------------------------------ --------- 11.8/15.4 MB 15.0 MB/s eta 0:00:01
   --------------------------------- ------ 12.8/15.4 MB 13.1 MB/s eta 0:00:01
   ---------------------------------- ----- 13.4/15.4 MB 12.1 MB/s eta 0:00:01
   ------------------------------------ --- 13.9/15.4 MB 10.4 MB/s eta 0:00:01
   ------------------------------------ --- 14.2/15.4 MB 9.7 MB/s eta 0:00:01
   -------------------------------------- - 14.7/15.4 MB 8.3 MB/s eta 0:00:01
   -------------------------------------- - 14.9/15.4 MB 7.8 MB/s eta 0:00:01
   ---------------------------------------  15.2/15.4 MB 7.1 MB/s eta 0:00:01
   ---------------------------------------- 15.4/15.4 MB 6.5 MB/s  0:00:02
Downloading s3transfer-0.19.2-py3-none-any.whl (90 kB)
Installing collected packages: botocore, s3transfer, boto3

  Attempting uninstall: botocore

    Found existing installation: botocore 1.40.46

   ---------------------------------------- 0/3 [botocore]
   ---------------------------------------- 0/3 [botocore]
   ---------------------------------------- 0/3 [botocore]
   ---------------------------------------- 0/3 [botocore]
    Uninstalling botocore-1.40.46:
   ---------------------------------------- 0/3 [botocore]
      Successfully uninstalled botocore-1.40.46
   ---------------------------------------- 0/3 [botocore]
   ---------------------------------------- 0/3 [botocore]
   ---------------------------------------- 0/3 [botocore]
   ---------------------------------------- 0/3 [botocore]
   ---------------------------------------- 0/3 [botocore]
   ---------------------------------------- 0/3 [botocore]
   ---------------------------------------- 0/3 [botocore]
   ---------------------------------------- 0/3 [botocore]
   ---------------------------------------- 0/3 [botocore]
   ---------------------------------------- 0/3 [botocore]
   ---------------------------------------- 0/3 [botocore]
   ---------------------------------------- 0/3 [botocore]
   ---------------------------------------- 0/3 [botocore]
   ---------------------------------------- 0/3 [botocore]
   ---------------------------------------- 0/3 [botocore]
   ---------------------------------------- 0/3 [botocore]
   ---------------------------------------- 0/3 [botocore]
   ---------------------------------------- 0/3 [botocore]
   ---------------------------------------- 0/3 [botocore]
   ---------------------------------------- 0/3 [botocore]
   ---------------------------------------- 0/3 [botocore]
   ---------------------------------------- 0/3 [botocore]
   ---------------------------------------- 0/3 [botocore]
   ------------- -------------------------- 1/3 [s3transfer]
   ------------- -------------------------- 1/3 [s3transfer]
   -------------------------- ------------- 2/3 [boto3]
   -------------------------- ------------- 2/3 [boto3]
   -------------------------- ------------- 2/3 [boto3]
   ---------------------------------------- 3/3 [boto3]

Successfully installed boto3-1.43.58 botocore-1.43.58 s3transfer-0.19.2
Note: you may need to restart the kernel to use updated packages.

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
aiobotocore 2.25.0 requires botocore<1.40.50,>=1.40.46, but you have botocore 1.43.58 which is incompatible.

In [53]:
# AWS Access key
# AWS security key
# bucket
# file details

import boto3
import pandas as pd
from io import StringIO

In [55]:
aws_access_key="AKIAUQZ2TY42GUNVSFN7"
aws_secret_key="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"
region="eu-north-1"

#create S3 client

s3=boto3.client("s3", aws_access_key_id=aws_access_key, aws_secret_access_key=aws_secret_key, region_name=region)

bucket_name="amit4688"
file_key="Bank Data.csv"

#read the file from the S3

response=s3.get_object(Bucket=bucket_name, Key=file_key)

#convert bytes to to string
csv_data=response["Body"].read().decode("utf-8")

df=pd.read_csv(StringIO(csv_data))

In [56]:
df

,Customer ID,Name,Surname,Gender,Age,Region,Job Classification,Date Joined,Balance
0,1,Simon,Walsh,Male,21,England,White Collar,05.Jan.15,113810.15
1,400000002,Jasmine,Miller,Female,34,Northern Ireland,Blue Collar,06.Jan.15,36919.73
2,100000003,Liam,Brown,Male,46,England,White Collar,07.Jan.15,101536.83
3,300000004,Trevor,Parr,Male,32,Wales,White Collar,08.Jan.15,1421.52
4,100000005,Deirdre,Pullman,Female,38,England,Blue Collar,09.Jan.15,35639.79
...,...,...,...,...,...,...,...,...,...
4011,200004012,Hannah,Springer,Female,50,Scotland,Other,30.Dec.15,59477.82
4012,200004013,Christian,Reid,Male,51,Scotland,Blue Collar,30.Dec.15,239.45
4013,300004014,Stephen,May,Male,33,Wales,Blue Collar,30.Dec.15,30293.19
4014,500004014,Ram,May,Male,33,Wales,Blue Collar,30.Dec.15,30293.19
4015,600004014,Ram,May,Male,33,Wales,Blue Collar,30.Dec.15,30293.19

In [57]:
#Access the API --- https://catfact.ninja/facts

#Print all the facts
#find the longest fact
#count of all the facts
#save them to a csv

import requests
url = "https://catfact.ninja/facts"
response=requests.get(url)
if response.status_code==200:
    data=response.json()
facts=[]
for i in data["data"]:
    print("facts :",i["fact"])
    facts.append(i["fact"])

facts : Unlike dogs, cats do not have a sweet tooth. Scientists believe this is due to a mutation in a key taste receptor.
facts : When a cat chases its prey, it keeps its head level. Dogs and humans bob their heads up and down.
facts : The technical term for a cat’s hairball is a “bezoar.”
facts : A group of cats is called a “clowder.”
facts : A cat can’t climb head first down a tree because every claw on a cat’s paw points the same way. To get down from a tree, a cat must back down.
facts : Cats make about 100 different sounds. Dogs make only about 10.
facts : Every year, nearly four million cats are eaten in Asia.
facts : There are more than 500 million domestic cats in the world, with approximately 40 recognized breeds.
facts : Approximately 24 cat skins can make a coat.
facts : While it is commonly thought that the ancient Egyptians were the first to domesticate cats, the oldest known pet cat was recently found in a 9,500-year-old grave on the Mediterranean island of Cyprus. This grave predates early Egyptian art depicting cats by 4,000 years or more.

In [60]:
data

{'current_page': 1,
 'data': [{'fact': 'Unlike dogs, cats do not have a sweet tooth. Scientists believe this is due to a mutation in a key taste receptor.',
   'length': 114},
  {'fact': 'When a cat chases its prey, it keeps its head level. Dogs and humans bob their heads up and down.',
   'length': 97},
  {'fact': 'The technical term for a cat’s hairball is a “bezoar.”',
   'length': 54},
  {'fact': 'A group of cats is called a “clowder.”', 'length': 38},
  {'fact': 'A cat can’t climb head first down a tree because every claw on a cat’s paw points the same way. To get down from a tree, a cat must back down.',
   'length': 142},
  {'fact': 'Cats make about 100 different sounds. Dogs make only about 10.',
   'length': 62},
  {'fact': 'Every year, nearly four million cats are eaten in Asia.',
   'length': 55},
  {'fact': 'There are more than 500 million domestic cats in the world, with approximately 40 recognized breeds.',
   'length': 100},
  {'fact': 'Approximately 24 cat skins can make a coat.', 'length': 43},
  {'fact': 'While it is commonly thought that the ancient Egyptians were the first to domesticate cats, the oldest known pet cat was recently found in a 9,500-year-old grave on the Mediterranean island of Cyprus. This grave predates early Egyptian art depicting cats by 4,000 years or more.',
   'length': 278}],
 'first_page_url': 'https://catfact.ninja/facts?page=1',
 'from': 1,
 'last_page': 34,
 'last_page_url': 'https://catfact.ninja/facts?page=34',
 'links': [{'url': None, 'label': 'Previous', 'active': False},
  {'url': 'https://catfact.ninja/facts?page=1', 'label': '1', 'active': True},
  {'url': 'https://catfact.ninja/facts?page=2', 'label': '2', 'active': False},
  {'url': 'https://catfact.ninja/facts?page=3', 'label': '3', 'active': False},
  {'url': 'https://catfact.ninja/facts?page=4', 'label': '4', 'active': False},
  {'url': 'https://catfact.ninja/facts?page=5', 'label': '5', 'active': False},
  {'url': 'https://catfact.ninja/facts?page=6', 'label': '6', 'active': False},
  {'url': 'https://catfact.ninja/facts?page=7', 'label': '7', 'active': False},
  {'url': 'https://catfact.ninja/facts?page=8', 'label': '8', 'active': False},
  {'url': 'https://catfact.ninja/facts?page=9', 'label': '9', 'active': False},
  {'url': 'https://catfact.ninja/facts?page=10',
   'label': '10',
   'active': False},
  {'url': None, 'label': '...', 'active': False},
  {'url': 'https://catfact.ninja/facts?page=33',
   'label': '33',
   'active': False},
  {'url': 'https://catfact.ninja/facts?page=34',
   'label': '34',
   'active': False},
  {'url': 'https://catfact.ninja/facts?page=2',
   'label': 'Next',
   'active': False}],
 'next_page_url': 'https://catfact.ninja/facts?page=2',
 'path': 'https://catfact.ninja/facts',
 'per_page': 10,
 'prev_page_url': None,
 'to': 10,
 'total': 332}

In [58]:
longest=max(facts, key=len)
longest

'While it is commonly thought that the ancient Egyptians were the first to domesticate cats, the oldest known pet cat was recently found in a 9,500-year-old grave on the Mediterranean island of Cyprus. This grave predates early Egyptian art depicting cats by 4,000 years or more.'

In [59]:
# Unit testing

# Functions

# Developer -- code
import unittest

In [61]:
def add(a,b):
    return a+b

In [62]:
class TestMath(unittest.TestCase):
    def test_add_positive(self):
        self.assertEqual(add(2,3),5)
    def test_add_negative(self):
        self.assertEqual(add(-2,-3),-5)
    def test_add_zero(self):
        self.assertEqual(add(5,0),5)

In [63]:
unittest.main(argv=[''], verbosity=2, exit=False)

test_add_negative (__main__.TestMath.test_add_negative) ... ok
test_add_positive (__main__.TestMath.test_add_positive) ... ok
test_add_zero (__main__.TestMath.test_add_zero) ... ok

----------------------------------------------------------------------
Ran 3 tests in 0.006s

OK

In [64]:
# Create a function that calculates the area of circle
def Circle(r):
    return 3.14*r*r

In [65]:
Circle(-5)

78.5

In [66]:
Circle(True)

3.14

In [67]:
Circle(3+2j)

(15.699999999999998+37.68j)

In [68]:
class TestMath(unittest.TestCase):
    #Test areas when radius>0
    def test_area(self):
        self.assertAlmostEqual(Circle(1),3.14)
        self.assertAlmostEqual(Circle(0),0)
        self.assertAlmostEqual(Circle(2.1), 3.14*2.1*2.1)

    # Negative values
    def test_values(self):
        self.assertRaises(ValueError,Circle,-2)

In [69]:
# Decorator Functions

# A function... And you want to use that function with other functions...
# decorators

import time
def brew_tea():
    start_time=time.time()
    print("Brewing tea....")
    time.sleep(1)
    print("Tea is ready")
    end_time=time.time()
    print("Task Time", end_time-start_time)

In [70]:
brew_tea()

Brewing tea....
Tea is ready
Task Time 1.001215934753418

In [80]:
# def make_matcha():
#     start_time=time.time()
#     print("Making mactha....")
#     time.sleep(2)
#     print("Matcha is ready")
#     end_time=time.time()
#     print("Task Time", end_time-start_time)

In [81]:
make_matcha()

Making mactha....
Matcha is ready

In [82]:
# so there is redundancy of code
def make_matcha():
    print("Making mactha....")
    time.sleep(2)
    print("Matcha is ready")

In [83]:
# Decorator time function
def timer_dec(base_fn):
    def enhanced_fn():
        start_time=time.time()
        base_fn()
        end_time=time.time()
        print("Task Time", end_time-start_time)
    return enhanced_fn()

In [84]:
timer_dec(make_matcha)

Making mactha....
Matcha is ready
Task Time 2.001204013824463

In [85]:
x=timer_dec(make_matcha)

Making mactha....
Matcha is ready
Task Time 2.00054669380188

In [86]:
x()

TypeError: 'NoneType' object is not callable

In [87]:
@timer_dec
def brew_tea():
    print("Brewing tea....")
    time.sleep(1)
    print("Tea is ready")

Brewing tea....
Tea is ready
Task Time 1.0011420249938965