In [1]:
import numpy as np
import pandas as pd

In [2]:
bank = pd.read_csv("P1-UK-Bank-Customers (1) (8).csv")

In [4]:
# Aggregations
bank.Balance     # SQL way
bank["Balance"]
# Both are same in dataframes  
bank["Balance"].sum()

np.float64(159622523.37)

In [5]:
bank["Balance"].mean()

np.float64(39766.4482735426)

In [7]:
# Groupby - for a summary of data
# Region wise sum of balance
bank.groupby("Region")["Balance"].sum()

Region
England             84833397.00
Northern Ireland     8335566.39
Scotland            44410730.72
Wales               22042829.26
Name: Balance, dtype: float64

In [11]:
# To convert to dataframe
# It resets the index and puts default indexing and converts Series to Dataframe
bank.groupby("Region")["Balance"].sum().reset_index()

             Region      Balance
0           England  84833397.00
1  Northern Ireland   8335566.39
2          Scotland  44410730.72
3             Wales  22042829.26

In [10]:
# Value_counts
bank["Region"].value_counts()

Region
England             2159
Scotland            1124
Wales                520
Northern Ireland     211
Name: count, dtype: int64

In [12]:
# Gender wise average age
bank.groupby("Gender")["Age"].mean()

Gender
Female    36.943753
Male      40.035104
Name: Age, dtype: float64

In [13]:
# To convert to dataframe
bank.groupby("Gender")["Age"].mean().reset_index()

   Gender        Age
0  Female  36.943753
1    Male  40.035104

In [14]:
# To group data by 2 levels on basis of balance
bank.groupby(["Region","Gender"])["Balance"].sum()

Region            Gender
England           Female    43627976.64
                  Male      41205420.36
Northern Ireland  Female     6086799.50
                  Male       2248766.89
Scotland          Female    11900747.68
                  Male      32509983.04
Wales             Female    11368010.25
                  Male      10674819.01
Name: Balance, dtype: float64

In [15]:
bank.groupby(["Region","Gender"])["Balance"].sum().reset_index()

             Region  Gender      Balance
0           England  Female  43627976.64
1           England    Male  41205420.36
2  Northern Ireland  Female   6086799.50
3  Northern Ireland    Male   2248766.89
4          Scotland  Female  11900747.68
5          Scotland    Male  32509983.04
6             Wales  Female  11368010.25
7             Wales    Male  10674819.01

In [20]:
# Multiple Aggregation
# Region wise Gender wise
bank.groupby("Region")[["Balance","Age"]].sum()
# region wise sum of balance , sum of age
# But here we generally don't calculate age sum we calculate avg. age

                      Balance    Age
Region
England           84833397.00  75107
Northern Ireland   8335566.39   6389
Scotland          44410730.72  55296
Wales             22042829.26  18193

In [17]:

type(bank.groupby(["Region","Gender"])["Balance"].sum())

pandas.core.series.Series

In [18]:

type(bank.groupby(["Region","Gender"])["Balance"].sum().reset_index())

pandas.core.frame.DataFrame

In [21]:
# Here we get sum and mean of balance and age both using agg function
bank.groupby("Region")[["Balance","Age"]].agg(["sum","mean"])

                      Balance                  Age
                          sum          mean    sum       mean
Region
England           84833397.00  39292.911996  75107  34.787865
Northern Ireland   8335566.39  39505.053981   6389  30.279621
Scotland          44410730.72  39511.326263  55296  49.195730
Wales             22042829.26  42390.056269  18193  34.986538

In [22]:
# Now we get sum of balance and mean of age using dictionary defining using key value pairs
bank.groupby("Region")[["Balance","Age"]].agg({"Balance":"sum","Age":"mean"})

                      Balance        Age
Region
England           84833397.00  34.787865
Northern Ireland   8335566.39  30.279621
Scotland          44410730.72  49.195730
Wales             22042829.26  34.986538

In [23]:
# WAP to fetch the avg. balance by job classification for the region where 
# we have highest avg balance
print(bank.columns)

Index(['Customer ID', 'Name', 'Surname', 'Gender', 'Age', 'Region',
       'Job Classification', 'Date Joined', 'Balance'],
      dtype='object')

In [32]:
# Region with highest avg balance
x = bank.groupby("Region")["Balance"].mean().idxmax()
# or 
r=bank.groupby("Region")["Balance"].mean().sort_values(ascending=False).reset_index().iloc[0,0]

In [33]:
bank.loc[bank.Region==r, :].groupby(["Region","Job Classification"])["Balance"].mean()

Region  Job Classification
Wales   Blue Collar           42566.395083
        Other                 39104.892947
        White Collar          43343.924656
Name: Balance, dtype: float64

In [35]:
# Pivot
summ = bank.groupby(["Region","Gender"])["Balance"].sum().reset_index()

In [ ]:
summ.pivot(index="Region",columns="Gender")

In [36]:
bank.pivot_table(index="Region",columns="Gender",values="Balance",aggfunc="sum")

Gender                 Female         Male
Region
England           43627976.64  41205420.36
Northern Ireland   6086799.50   2248766.89
Scotland          11900747.68  32509983.04
Wales             11368010.25  10674819.01

In [37]:
# Load the order sheets from the excel 
orders = pd.read_excel("Sample - Superstore (1) (1) (1).xlsx", sheet_name="Orders")

In [38]:
# Tasks
# 1. Fetch the unique category
# 2. Fetch the unique category and sub category
# 3. Fetch the top 5 selling products by sales
# 4. Create a crosstab to show sales by categroy and Region
# 5. Fetch the custmer Name , Sales for category "Furniture" and Region "East"

In [39]:
orders.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

In [53]:
# 1. Fetch the unique category
# orders["Category"].unique()
orders.Category.unique()

array(['Furniture', 'Office Supplies', 'Technology'], dtype=object)

In [57]:
# 2. Fetch the unique category and sub category
# Unique() only works on one category and not two so we can use drop_duplicates()
orders[["Category","Sub-Category"]].drop_duplicates()
# loc gives data in row and columns 
orders.loc[:, ["Category", "Sub-Category"]].drop_duplicates()

            Category Sub-Category
0          Furniture    Bookcases
1          Furniture       Chairs
2    Office Supplies       Labels
3          Furniture       Tables
4    Office Supplies      Storage
5          Furniture  Furnishings
6    Office Supplies          Art
7         Technology       Phones
8    Office Supplies      Binders
9    Office Supplies   Appliances
12   Office Supplies        Paper
26        Technology  Accessories
30   Office Supplies    Envelopes
53   Office Supplies    Fasteners
138  Office Supplies     Supplies
165       Technology     Machines
335       Technology      Copiers

In [60]:
# 3. Fetch the top 5 selling products by sales
orders.groupby("Product Name")["Sales"].sum().sort_values(ascending=False).reset_index().head()

                                        Product Name      Sales
0              Canon imageCLASS 2200 Advanced Copier  61599.824
1  Fellowes PB500 Electric Punch Plastic Comb Bin...  27453.384
2  Cisco TelePresence System EX90 Videoconferenci...  22638.480
3       HON 5400 Series Task Chairs for Big and Tall  21870.576
4         GBC DocuBind TL300 Electric Binding System  19823.479

In [63]:
# 4. Create a crosstab to show sales by categroy and Region

orders.pivot_table(index="Category", columns="Region", values="Sales", aggfunc="sum")

Region               Central        East       South         West
Category
Furniture        163797.1638  208291.204  117298.684  252612.7435
Office Supplies  167026.4150  205516.055  125651.313  220853.2490
Technology       170416.3120  264973.981  148771.908  251991.8320

In [65]:
# 5. Fetch the custmer Name , Sales for category "Furniture" and Region "East"
orders.loc[(orders.Region=="East")&(orders.Category=="Furniture"), ["Customer Name","Sales"]]

        Customer Name     Sales
23    Sandra Flanagan    71.372
27    Tracy Blumstein  3083.430
29    Tracy Blumstein   124.200
57    Ted Butterfield   319.410
96     Parhena Norris    96.530
...               ...       ...
9897        Liz Preis   466.320
9898        Liz Preis    82.640
9899   Mike Pelletier   330.588
9938     Noel Staavos    60.350
9964     Harold Engle    13.400

[601 rows x 2 columns]

In [66]:
orders_newreg = pd.read_excel("Sample - Superstore_New Region (9) (1) (1).xlsx", sheet_name="Orders")

In [69]:

orders_newreg.dropna(inplace=True)

In [70]:
orders_newreg

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20
4,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
5,15,US-2015-118983,2015-11-22 00:00:00,2015-11-26 00:00:00,Standard Class,HP-14815,Harold Pawlan,Home Office,United States,Fort Worth,...,761060,New Region,OFF-AP-10002311,Office Supplies,Appliances,Holmes Replacement Filter for HEPA Air Cleaner...,68.81,5,0.8,-123.858
6,16,US-2015-118983,2015-11-22 00:00:00,2015-11-26 00:00:00,Standard Class,HP-14815,Harold Pawlan,Home Office,United States,Fort Worth,...,761060,New Region,OFF-BI-10000756,Office Supplies,Binders,Storex DuraTech Recycled Plastic Frosted Binders,2.544,3,0.8,-3.816
7,17,CA-2014-105893,2014-11-11 00:00:00,2014-11-18 00:00:00,Standard Class,PK-19075,Pete Kriz,Consumer,United States,Madison,...,537110,New Region,OFF-ST-10004186,Office Supplies,Storage,"Stur-D-Stor Shelving, Vertical 5-Shelf: 72""H x...",665.88,6,0,13.3176
8,22,CA-2016-137330,2016-12-09 00:00:00,2016-12-13 00:00:00,Standard Class,KB-16585,Ken Black,Corporate,United States,Fremont,...,680250,New Region,OFF-AR-10000246,Office Supplies,Art,Newell 318,19.46,7,0,5.0596
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2326,9983,US-2016-157728,2016-09-22 00:00:00,2016-09-28 00:00:00,Standard Class,RC-19960,Ryan Crowe,Consumer,United States,Grand Rapids,...,495050,New Region,OFF-PA-10002195,Office Supplies,Paper,"RSVP Cards & Envelopes, Blank White, 8-1/2"" X ...",35.56,7,0,16.7132
2327,9984,US-2016-157728,2016-09-22 00:00:00,2016-09-28 00:00:00,Standard Class,RC-19960,Ryan Crowe,Consumer,United States,Grand Rapids,...,495050,New Region 2,TEC-PH-10001305,Technology,Phones,Panasonic KX TS208W Corded phone,97.98,2,0,27.4344
2328,9984,US-2016-157728,2016-09-22 00:00:00,2016-09-28 00:00:00,Standard Class,RC-19960,Ryan Crowe,Consumer,United States,Grand Rapids,...,495050,New Region 2,TEC-PH-10001305,Technology,Phones,Panasonic KX TS208W Corded phone,97.98,2,0,27.4344
2329,9984,US-2016-157728,2016-09-22 00:00:00,2016-09-28 00:00:00,Standard Class,RC-19960,Ryan Crowe,Consumer,United States,Grand Rapids,...,495050,New Region 2,TEC-PH-10001305,Technology,Phones,Panasonic KX TS208W Corded phone,97.98,2,0,27.4344
2330,9984,US-2016-157728,2016-09-22 00:00:00,2016-09-28 00:00:00,Standard Class,RC-19960,Ryan Crowe,Consumer,United States,Grand Rapids,...,495050,New Region 2,TEC-PH-10001305,Technology,Phones,Panasonic KX TS208W Corded phone,97.98,2,0,27.4344

In [71]:
orders_newreg.columns = orders_newreg.iloc[0,:]

In [72]:
orders_newreg

4,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
4,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
5,15,US-2015-118983,2015-11-22 00:00:00,2015-11-26 00:00:00,Standard Class,HP-14815,Harold Pawlan,Home Office,United States,Fort Worth,...,761060,New Region,OFF-AP-10002311,Office Supplies,Appliances,Holmes Replacement Filter for HEPA Air Cleaner...,68.81,5,0.8,-123.858
6,16,US-2015-118983,2015-11-22 00:00:00,2015-11-26 00:00:00,Standard Class,HP-14815,Harold Pawlan,Home Office,United States,Fort Worth,...,761060,New Region,OFF-BI-10000756,Office Supplies,Binders,Storex DuraTech Recycled Plastic Frosted Binders,2.544,3,0.8,-3.816
7,17,CA-2014-105893,2014-11-11 00:00:00,2014-11-18 00:00:00,Standard Class,PK-19075,Pete Kriz,Consumer,United States,Madison,...,537110,New Region,OFF-ST-10004186,Office Supplies,Storage,"Stur-D-Stor Shelving, Vertical 5-Shelf: 72""H x...",665.88,6,0,13.3176
8,22,CA-2016-137330,2016-12-09 00:00:00,2016-12-13 00:00:00,Standard Class,KB-16585,Ken Black,Corporate,United States,Fremont,...,680250,New Region,OFF-AR-10000246,Office Supplies,Art,Newell 318,19.46,7,0,5.0596
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2326,9983,US-2016-157728,2016-09-22 00:00:00,2016-09-28 00:00:00,Standard Class,RC-19960,Ryan Crowe,Consumer,United States,Grand Rapids,...,495050,New Region,OFF-PA-10002195,Office Supplies,Paper,"RSVP Cards & Envelopes, Blank White, 8-1/2"" X ...",35.56,7,0,16.7132
2327,9984,US-2016-157728,2016-09-22 00:00:00,2016-09-28 00:00:00,Standard Class,RC-19960,Ryan Crowe,Consumer,United States,Grand Rapids,...,495050,New Region 2,TEC-PH-10001305,Technology,Phones,Panasonic KX TS208W Corded phone,97.98,2,0,27.4344
2328,9984,US-2016-157728,2016-09-22 00:00:00,2016-09-28 00:00:00,Standard Class,RC-19960,Ryan Crowe,Consumer,United States,Grand Rapids,...,495050,New Region 2,TEC-PH-10001305,Technology,Phones,Panasonic KX TS208W Corded phone,97.98,2,0,27.4344
2329,9984,US-2016-157728,2016-09-22 00:00:00,2016-09-28 00:00:00,Standard Class,RC-19960,Ryan Crowe,Consumer,United States,Grand Rapids,...,495050,New Region 2,TEC-PH-10001305,Technology,Phones,Panasonic KX TS208W Corded phone,97.98,2,0,27.4344
2330,9984,US-2016-157728,2016-09-22 00:00:00,2016-09-28 00:00:00,Standard Class,RC-19960,Ryan Crowe,Consumer,United States,Grand Rapids,...,495050,New Region 2,TEC-PH-10001305,Technology,Phones,Panasonic KX TS208W Corded phone,97.98,2,0,27.4344

In [73]:
orders_newreg = orders_newreg.iloc[1:,]

In [74]:
orders_newreg

4,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
5,15,US-2015-118983,2015-11-22 00:00:00,2015-11-26 00:00:00,Standard Class,HP-14815,Harold Pawlan,Home Office,United States,Fort Worth,...,761060,New Region,OFF-AP-10002311,Office Supplies,Appliances,Holmes Replacement Filter for HEPA Air Cleaner...,68.81,5,0.8,-123.858
6,16,US-2015-118983,2015-11-22 00:00:00,2015-11-26 00:00:00,Standard Class,HP-14815,Harold Pawlan,Home Office,United States,Fort Worth,...,761060,New Region,OFF-BI-10000756,Office Supplies,Binders,Storex DuraTech Recycled Plastic Frosted Binders,2.544,3,0.8,-3.816
7,17,CA-2014-105893,2014-11-11 00:00:00,2014-11-18 00:00:00,Standard Class,PK-19075,Pete Kriz,Consumer,United States,Madison,...,537110,New Region,OFF-ST-10004186,Office Supplies,Storage,"Stur-D-Stor Shelving, Vertical 5-Shelf: 72""H x...",665.88,6,0,13.3176
8,22,CA-2016-137330,2016-12-09 00:00:00,2016-12-13 00:00:00,Standard Class,KB-16585,Ken Black,Corporate,United States,Fremont,...,680250,New Region,OFF-AR-10000246,Office Supplies,Art,Newell 318,19.46,7,0,5.0596
9,23,CA-2016-137330,2016-12-09 00:00:00,2016-12-13 00:00:00,Standard Class,KB-16585,Ken Black,Corporate,United States,Fremont,...,680250,New Region,OFF-AP-10001492,Office Supplies,Appliances,"Acco Six-Outlet Power Strip, 4' Cord Length",60.34,7,0,15.6884
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2326,9983,US-2016-157728,2016-09-22 00:00:00,2016-09-28 00:00:00,Standard Class,RC-19960,Ryan Crowe,Consumer,United States,Grand Rapids,...,495050,New Region,OFF-PA-10002195,Office Supplies,Paper,"RSVP Cards & Envelopes, Blank White, 8-1/2"" X ...",35.56,7,0,16.7132
2327,9984,US-2016-157728,2016-09-22 00:00:00,2016-09-28 00:00:00,Standard Class,RC-19960,Ryan Crowe,Consumer,United States,Grand Rapids,...,495050,New Region 2,TEC-PH-10001305,Technology,Phones,Panasonic KX TS208W Corded phone,97.98,2,0,27.4344
2328,9984,US-2016-157728,2016-09-22 00:00:00,2016-09-28 00:00:00,Standard Class,RC-19960,Ryan Crowe,Consumer,United States,Grand Rapids,...,495050,New Region 2,TEC-PH-10001305,Technology,Phones,Panasonic KX TS208W Corded phone,97.98,2,0,27.4344
2329,9984,US-2016-157728,2016-09-22 00:00:00,2016-09-28 00:00:00,Standard Class,RC-19960,Ryan Crowe,Consumer,United States,Grand Rapids,...,495050,New Region 2,TEC-PH-10001305,Technology,Phones,Panasonic KX TS208W Corded phone,97.98,2,0,27.4344
2330,9984,US-2016-157728,2016-09-22 00:00:00,2016-09-28 00:00:00,Standard Class,RC-19960,Ryan Crowe,Consumer,United States,Grand Rapids,...,495050,New Region 2,TEC-PH-10001305,Technology,Phones,Panasonic KX TS208W Corded phone,97.98,2,0,27.4344

In [75]:
final_data = pd.concat([orders,orders_newreg], axis = 0)

In [76]:
final_data

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08 00:00:00,2016-11-11 00:00:00,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.0,41.9136
1,2,CA-2016-152156,2016-11-08 00:00:00,2016-11-11 00:00:00,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,3,0.0,219.582
2,3,CA-2016-138688,2016-06-12 00:00:00,2016-06-16 00:00:00,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.62,2,0.0,6.8714
3,4,US-2015-108966,2015-10-11 00:00:00,2015-10-18 00:00:00,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.031
4,5,US-2015-108966,2015-10-11 00:00:00,2015-10-18 00:00:00,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.368,2,0.2,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2326,9983,US-2016-157728,2016-09-22 00:00:00,2016-09-28 00:00:00,Standard Class,RC-19960,Ryan Crowe,Consumer,United States,Grand Rapids,...,495050,New Region,OFF-PA-10002195,Office Supplies,Paper,"RSVP Cards & Envelopes, Blank White, 8-1/2"" X ...",35.56,7,0,16.7132
2327,9984,US-2016-157728,2016-09-22 00:00:00,2016-09-28 00:00:00,Standard Class,RC-19960,Ryan Crowe,Consumer,United States,Grand Rapids,...,495050,New Region 2,TEC-PH-10001305,Technology,Phones,Panasonic KX TS208W Corded phone,97.98,2,0,27.4344
2328,9984,US-2016-157728,2016-09-22 00:00:00,2016-09-28 00:00:00,Standard Class,RC-19960,Ryan Crowe,Consumer,United States,Grand Rapids,...,495050,New Region 2,TEC-PH-10001305,Technology,Phones,Panasonic KX TS208W Corded phone,97.98,2,0,27.4344
2329,9984,US-2016-157728,2016-09-22 00:00:00,2016-09-28 00:00:00,Standard Class,RC-19960,Ryan Crowe,Consumer,United States,Grand Rapids,...,495050,New Region 2,TEC-PH-10001305,Technology,Phones,Panasonic KX TS208W Corded phone,97.98,2,0,27.4344
2330,9984,US-2016-157728,2016-09-22 00:00:00,2016-09-28 00:00:00,Standard Class,RC-19960,Ryan Crowe,Consumer,United States,Grand Rapids,...,495050,New Region 2,TEC-PH-10001305,Technology,Phones,Panasonic KX TS208W Corded phone,97.98,2,0,27.4344

In [77]:
final_data.Region.unique()

array(['South', 'West', 'Central', 'East', 'New Region', 'New Region 2'],
      dtype=object)

In [78]:

df1=pd.DataFrame({"ID":[1,2,3,4], "Name":["A","B","C","D"]})
df2=pd.DataFrame({"ID":[1,2,3,5], "Age":[21,22,23,24]})

In [79]:
pd.merge(df1,df2, how="inner")

   ID Name  Age
0   1    A   21
1   2    B   22
2   3    C   23

In [80]:
pd.merge(df1,df2, how="left")

   ID Name   Age
0   1    A  21.0
1   2    B  22.0
2   3    C  23.0
3   4    D   NaN

In [81]:
pd.merge(df1,df2, how="outer")

   ID Name   Age
0   1    A  21.0
1   2    B  22.0
2   3    C  23.0
3   4    D   NaN
4   5  NaN  24.0

In [82]:
# to load data from db mysql
pip install mysql-connector-python

SyntaxError: invalid syntax (2444761285.py, line 2)

In [83]:
import mysql.connector

ModuleNotFoundError: No module named 'mysql'

In [ ]:
connection = mysql.connector.connect(
    host="localhost",
    user="root",
    password="1234",
    database="store"
)

In [ ]:
cursor = connection.cursor()